services:

  ollama:
    # image: ollama/ollama:latest
    image: ollama/ollama:0.13.1
    container_name: ollama-rag
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  open_notebook:
    # image: lfnovo/open_notebook:v1-latest-single
    image: lfnovo/open_notebook:1.2.3-single
    container_name: open-notebook
    ports:
      - "8502:8502"  # Web UI
      - "5055:5055"  # API
    environment:
      - API_URL=http://127.0.0.1:5055
      - OLLAMA_API_BASE=http://ollama-rag:11434
      # Database connection (required)
      - SURREAL_URL=ws://localhost:8000/rpc
      - SURREAL_USER=root
      - SURREAL_PASSWORD=root
      - SURREAL_NAMESPACE=open_notebook
      - SURREAL_DATABASE=production
    volumes:
      - notebook-data:/app/data
      - surreal-data:/mydata
    depends_on:
      - ollama

volumes:
  ollama-data:
    name: shared-ollama-data
  notebook-data:
  surreal-data:

